"""init schema

Revision ID: b812235a789e
Revises: 
Create Date: 2026-09-02 09:23:51.378781
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b812235a789e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_studentId'), 'alerts', ['studentId'], unique=False)
    op.create_table('classes',
    sa.Column('classId', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('studentCount', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=False),
    sa.Column('courseId', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('classId')
    )
    op.create_table('courses',
    sa.Column('courseId', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('teacherId', sa.String(length=32), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('courseId')
    )
    op.create_table('intervention_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planId', sa.String(length=32), nullable=False),
    sa.Column('studentId', sa.String(length=32), nullable=False),
    sa.Column('teacherId', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_plans_studentId'), 'intervention_plans', ['studentId'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('kpId', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parentId', sa.String(length=32), nullable=False),
    sa.Column('courseId', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('preKp', sa.Text(), nullable=False),
    sa.Column('postKp', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('kpId')
    )
    op.create_table('mastery_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.String(length=32), nullable=False),
    sa.Column('kpId', sa.String(length=32), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('correctRate', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastery_records_kpId'), 'mastery_records', ['kpId'], unique=False)
    op.create_index(op.f('ix_mastery_records_studentId'), 'mastery_records', ['studentId'], unique=False)
    op.create_table('questions',
    sa.Column('qId', sa.String(length=32), nullable=False),
    sa.Column('kpId', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('qId')
    )
    op.create_index(op.f('ix_questions_kpId'), 'questions', ['kpId'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.String(length=32), nullable=False),
    sa.Column('qId', sa.String(length=32), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_studentId'), 'submissions', ['studentId'], unique=False)
    op.create_table('users',
    sa.Column('userId', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('avatar_char', sa.String(length=4), nullable=False),
    sa.Column('org', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('dept', sa.String(length=128), nullable=False),
    sa.Column('classes_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('view_snapshots',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_snapshots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_submissions_studentId'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_questions_kpId'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_mastery_records_studentId'), table_name='mastery_records')
    op.drop_index(op.f('ix_mastery_records_kpId'), table_name='mastery_records')
    op.drop_table('mastery_records')
    op.drop_table('knowledge_points')
    op.drop_index(op.f('ix_intervention_plans_studentId'), table_name='intervention_plans')
    op.drop_table('intervention_plans')
    op.drop_table('courses')
    op.drop_table('classes')
    op.drop_index(op.f('ix_alerts_studentId'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
